#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#blog_list:
#  path:     /blog
#  controller: App\Controller\BlogController::list
#
#blog_show:
#  path:     /blog/{slug}
#  controller: App\Controller\BlogController::show